#version: '3.8'

services:
  simubridge-sopa:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/insm-tum/simubridge--sopa-extension:main
    container_name: simubridge-sopa
    depends_on:
      - scylla-sopa-extended
    ports:
      - "3000:3000"
    networks:
      - app-network
  scylla-sopa-extended:
    build: 
      dockerfile_inline: |
        FROM ghcr.io/insm-tum/scylla-container:main
        ADD https://github.com/KoettingNina/Scylla-Plugin--SOPA/releases/download/v1.0.0/sopa-0.1.2-SNAPSHOT.jar /app/plugins/scylla-plugin--sopa.jar
        
    container_name: scylla-sopa-extended
    ports:
      - "8080:8080"
    networks:
      - app-network
  simod:
    build: 
      dockerfile_inline: |
        FROM nokal/simod-http:3.2.1-prerelease38
        ADD https://raw.githubusercontent.com/INSM-TUM/SimuBridge/main/simod_http_augemented/main.py /usr/src/Simod/src/simod_http/main.py
    container_name: simod-cors
    ports:
      - "8880:80"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge