name: CI

on: [push]

jobs:
  test:
    name: Cypress Test
    timeout-minutes: 10
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [20.x]

    steps:
      #- uses: actions/checkout@v3
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        # uses: actions/setup-node@v3
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}           
          cache: 'npm'
          
      # - name: Checkout
      #  uses: actions/checkout@v2
      
      - name: Node install
        run: npm install --legacy-peer-deps
        
      - name: Cypress run
        # uses: cypress-io/github-action@v5
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          install: false
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
      - name: Upload Failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
